global:
  scrape_interval: 5s  # Scrape targets every 5 seconds

scrape_configs:
  - job_name: 'kafka_producer'
    static_configs:
      - targets: ['localhost:8000']  # Producer metrics endpoint

  - job_name: 'kafka_consumer'
    static_configs:
      - targets: ['localhost:8001']  # Consumer metrics endpoint
